- name: "Setting up Postfix"
  hosts: server
  become: true
  tasks:
  - name: "Installing Postfix"
    apt:
      name: "{{ item }}"
      update_cache: true
    loop:
    - "postfix"
    - "sasl2-bin"
    - "postfix-ldap"
  - name: "Create mail folder"
    file:
      state: directory
      path: /home/mail
      owner: root
      group: root
      mode: 0666
  - name: "Configuring main.cf"
    template:
      src: templates/main.cf.j2
      dest: /etc/postfix/main.cf
      mode: 0644
      owner: root
      group: root
  - name: "Configuring master.cf"
    template:
      src: templates/master.cf.j2
      dest: /etc/postfix/master.cf
      mode: 0644
      owner: root
      group: root
  - name: Generate virtual lookup configs
    template:
      src: "templates/ldap/{{ item }}.j2"
      dest: /etc/postfix/ldap/{{ item }}
      owner: postfix
      group: postfix
      mode: 0400
    loop:
    - virtual_uid_maps
    - virtual_mailbox_maps
    - virtual_alias_maps
    - virtual_alias_domains
    - smtpd_sender_login_maps
  - name: Copy LDAP CA
    copy:
      src: files/server/etc/ldap/CA.pem
      dest: /etc/postfix/ldap/CA.pem
      owner: root
      group: root
      mode: 0404
  - name: "Create CA folder for postfix"
    file:
      state: directory
      path: /var/spool/postfix/etc/ldap
  - name: "Make the CA visible to postfix"
    copy:
      src: files/var-spool-postfix-etc-postfix-ldap.mount
      dest: /etc/systemd/system/var-spool-postfix-etc-postfix-ldap.mount
      mode: 0644
  - name: "Reload daemons"
    systemd:
      daemon_reload: true
      enabled: yes
      state: restarted
      name: var-spool-postfix-etc-postfix-ldap.mount
  - name: "Restarting Postfix"
    service:
      name: "postfix"
      state: "reloaded"
- name: "Setting up Dovecot"
  hosts: dovecot
  become: true
  tasks:
  - name: "Installing Dovecot"
    apt:
      name: "{{ item }}"
      update_cache: true
    loop:
    - "dovecot-core"
    - "dovecot-imapd"
    - "dovecot-pop3d"
    - "dovecot-lmtpd"
    - "dovecot-ldap"
  - name: "Configuring dovecot.conf"
    template:
      src: templates/dovecot.conf.j2
      dest: "/etc/dovecot/dovecot.conf"
      mode: 0644
      owner: root
      group: root
  - name: "Configuring conf.d"
    template:
      src: "templates/{{ item }}.j2"
      dest: "/etc/dovecot/conf.d/{{ item }}"
      mode: 0644
      owner: root
      group: root
    loop:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
  - name: "Generating LDAP config"
    template:
      src: templates/dovecot-ldap.conf.ext.j2
      dest: /etc/dovecot/dovecot-ldap.conf.ext
      mode: 0600
      owner: root
      group: root
  - name: Copy LDAP CA
    copy:
      src: files/server/etc/ldap/CA.pem
      dest: /etc/dovecot
      owner: root
      group: root
      mode: 0404
  - name: "Create mail folder"
    file:
      state: directory
      path: /home/mail
      owner: root
      group: root
      mode: 0777
  - name: "Restarting dovecot"
    service:
      name: "dovecot"
      state: "restarted"