- name: Installing LDAP server
  hosts: server
  become: true
  vars:
    ldap_auth:
      bind_dn: "cn=admin,dc=clt,dc=lan"
      bind_pw: "asdf"
    ldap_groups:
    - ou: mail
      dc: clt.lan
    ldap_accounts:
    - uid: mailuser
      ou: mail
      dc: clt.lan
    - uid: anothermail
      ou: mail
      dc: clt.lan
  tasks:
  - name: Openldap conf
    debconf:
      name: "slapd"
      question: 'slapd/no_configuration'
      value: "false"
      vtype: boolean
  - name: Set openldap password
    debconf:
      name: "slapd"
      question: 'slapd/password1'
      value: "{{ ldap_auth.bind_pw }}"
      vtype: password
  - name: Confirm openldap password
    debconf:
      name: "slapd"
      question: 'slapd/password2'
      value: "{{ ldap_auth.bind_pw }}"
      vtype: password
  - name: Set openldap domain
    debconf:
      name: "slapd"
      question: 'slapd/domain'
      value: clt.lan
      vtype: string
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - slapd
      - ldap-utils
      - python3-ldap
  - name: Copy config password
    template:
      src: templates/config_pass.ldif.j2
      dest: config_pass.ldif
  - name: Change config password
    command: "ldapmodify -Y EXTERNAL -H ldapi:/// -f config_pass.ldif"
  - name: Check if schema is already installed
    command: "ldapsearch -D cn=admin,cn=config -w {{ ldap_auth.bind_pw }} -H ldapi:/// -b \"cn=config\" -LLL objectClass=olcSchemaConfig dn"
    register: schema_search
  - name: "Save result"
    set_fact:
      postfix_schema: "{{ schema_search.stdout.split(\"\n\n\") | select('search', 'postfix,cn=schema,cn=config') | length > 0 }}"
  - name: Copy postfix_schema
    copy:
      src: files/postfix_schema.ldif
      dest: /tmp/postfix_schema.ldif
    when: not postfix_schema
  - name: Register postfix_schema
    command: "ldapadd -D cn=admin,cn=config -w {{ ldap_auth.bind_pw }} -H ldapi:/// -f /tmp/postfix_schema.ldif"
    when: not postfix_schema
  - name: Adding groups
    ldap_entry:
      dn: "{{ item.keys() | zip(item.values()) | map('join', '=') | join(',') | regex_replace('\\.', ',dc=') }}"
      objectClass:
        - organizationalUnit
      state: present
      bind_dn: "{{ ldap_auth.bind_dn }}"
      bind_pw: "{{ ldap_auth.bind_pw }}"
    loop: "{{ ldap_groups }}"
  - name: Remove accounts from previous tries
    ldap_entry:
      dn: "{{ item.keys() | zip(item.values()) | map('join', '=') | join(',') | regex_replace('\\.', ',dc=') }}"
      state: absent
      bind_dn: "{{ ldap_auth.bind_dn }}"
      bind_pw: "{{ ldap_auth.bind_pw }}"
    loop: "{{ ldap_accounts }}"
  - name: Add accounts
    ldap_entry:
      dn: "{{ item.keys() | zip(item.values()) | map('join', '=') | join(',') | regex_replace('\\.', ',dc=') }}"
      objectClass:
      - account
      - posixAccount
      - postfixUser
      attributes:
        cn: "{{ item.uid }}"
        mailacceptinggeneralid: "{{ item.uid }}@{{ item.dc }}"
        maildrop: "{{ item.uid }}@{{ item.dc }}"
        uid: "{{ item.uid }}"
        homedirectory: "/home/mail/{{ item.uid }}"
        uidnumber: "{{ 20000 + idx }}"
        gidnumber: "{{ 20000 + idx }}"
        userPassword: "{{ ldap_auth.bind_pw }}"
      state: present
      bind_dn: "{{ ldap_auth.bind_dn }}"
      bind_pw: "{{ ldap_auth.bind_pw }}"
    loop: "{{ ldap_accounts }}"
    loop_control:
      index_var: idx
  - name: Add postfix reader object
    ldap_entry:
      dn: "cn=mailAccountReader,dc=clt,dc=lan"
      objectClass:
        - organizationalRole
      state: present
      bind_dn: "{{ ldap_auth.bind_dn }}"
      bind_pw: "{{ ldap_auth.bind_pw }}"
  - name: Add password
    ldap_attrs:
      dn: "cn=mailAccountReader,dc=clt,dc=lan"
      state: exact
      attributes:
        objectClass:
        - organizationalRole
        - simpleSecurityObject
        userPassword: "{{ ldap_auth.bind_pw }}"
      bind_dn: "{{ ldap_auth.bind_dn }}"
      bind_pw: "{{ ldap_auth.bind_pw }}"
  - name: Copy slapd.conf
    template:
      src: templates/slapd.conf.j2
      dest: /etc/ldap/slapd.conf
  - name: Create CA private key
    community.crypto.openssl_privatekey:
      path: /etc/ldap/CA.key
      mode: 0400
      owner: openldap
      group: openldap
  - name: Create CA certificate
    community.crypto.x509_certificate:
      path: /etc/ldap/CA.pem
      privatekey_path: /etc/ldap/CA.key
      provider: selfsigned
      mode: 0404
      owner: openldap
      group: openldap
  - name: Create LDAP private key
    community.crypto.openssl_privatekey:
      path: /etc/ldap/ldap.key
      mode: 0400
      owner: openldap
      group: openldap
  - name: Create LDAP CSR
    community.crypto.openssl_csr:
      privatekey_path: /etc/ldap/ldap.key
      common_name: ldap.clt.lan
      path: /etc/ldap/ldap.csr
      mode: 0400
      owner: openldap
      group: openldap
  - name: Create LDAP certificate
    community.crypto.x509_certificate:
      csr_path: /etc/ldap/ldap.csr
      provider: ownca
      ownca_path: /etc/ldap/CA.pem
      ownca_privatekey_path: /etc/ldap/CA.key
      path: /etc/ldap/ldap.crt
      mode: 0400
      owner: openldap
      group: openldap
  - name: Add TLS cert path to config
    ldap_attrs:
      dn: "cn=config"
      state: exact
      attributes:
        olcTLSCACertificateFile: /etc/ldap/CA.pem
        olcTLSCertificateKeyFile: /etc/ldap/ldap.key
        olcTLSCertificateFile: /etc/ldap/ldap.crt
  - name: Use CA
    copy:
      src: files/ldap.conf
      dest: /etc/ldap/ldap.conf
      mode: 0644
      owner: root
      group: root
  - name: Restart slapd
    service:
      name: slapd
      state: restarted